### PR TITLE
react native

### PR DESCRIPTION
**Pull request by happyudong555**
react native is mobile application framework from facebook that you can build ios and android application on this framework with Java script ES6. including react native has native UI components for native design. **#hacktoberfest**

### CODE REVIEW

**Review by jgcmarins — COMMENTED** [review]
I don't think this makes sense

**Comment by wiput1999** [comment]
@jaburcodes  @jgcmarins I think this PR should tag as invalid PR

**Comment by annibuliful** [comment]
Please set tag invalid. I think it just a spam

**Comment by socksrust** [comment]
Thnx @jgcmarins @lagmanzaza @wiput1999

**Pull request closed without merging**
